server:
  port: ${SERVER_PORT}

application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}

info:
  app:
    name: ${APP_TITLE}
    description: ${APP_TITLE} ${APP_VERSION}
    version: ${APP_VERSION}

spring:
  application:
    name: product-service

  profiles:
    active: dev

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB

  config:
    import: configserver:http://localhost:8888/

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      categoryClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      WorkspaceClientgetWorkspaceByWorkspaceIdStringUUID:
        timeout-duration: 45s
  retry:
    instances:
      WorkspaceClientgetWorkspaceByWorkspaceIdStringUUID:
        max-attempts: 5
        wait-duration: 1s
        retry-exceptions:
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
  bulkhead:
    instances:
      WorkspaceClientgetWorkspaceByWorkspaceIdStringUUID:
        max-concurrent-calls: 50
        max-wait-duration: 2s
category-url:
  url: http://localhost:8080

rest:
  file-service:
    base-url: ${FILE_SERVICE_BASE_URL}
file:
  supported-extension: jpg,png,jpeg,webp,gif
  base-uri: ${FILE_BASE_URI}
  download-uri: ${FILE_DOWNLOAD_URI}