server:
  port: ${SERVER_PORT}

application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}

info:
  app:
    name: ${APP_TITLE}
    description: ${APP_TITLE} ${APP_VERSION}
    version: ${APP_VERSION}

spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8888/

#  security:
#    user:
#      name: efree
#      password: efree@123

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  main:
#    web-application-type: servlet #FOR SERVLET-BASED GATEWAY
    web-application-type: reactive #FOR REACTIVE GATEWAY
    allow-bean-definition-overriding: true #OVERRIDE WebSecurityConfiguration

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

rest:
  user-service:
    base-url: ${USER_SERVICE_BASE_URL}

access-token:
  private: ${ACCESS_TOKEN_PRIVATE}
  public: ${ACCESS_TOKEN_PUBLIC}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE}
  public: ${REFRESH_TOKEN_PUBLIC}