server:
  port: ${SERVER_PORT}

application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}

info:
  app:
    name: ${APP_TITLE}
    description: ${APP_TITLE} ${APP_VERSION}
    version: ${APP_VERSION}

spring:
  application:
    name: category-service

  profiles:
    active: prod

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      maximum-pool-size: 20 # For CP Hikari
      connection-timeout: 10000 # 10s
      idle-timeout: 10000 # 10s
      minimum-idle: 10
      max-lifetime: 300000 # 300s

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        able_lazy_load_no_trans: true

  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB

  config:
#    import: optional:configserver:http://localhost:8888/
    import: optional:configserver:http://configuration-service-svc.microservice.svc.prod:8888/

file:
  supported-extension: jpg,png,jpeg,webp,gif
  base-uri: ${FILE_BASE_URI}
  download-uri: ${FILE_DOWNLOAD_URI}

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}

  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

rest:
  file-service:
    base-url: ${FILE_SERVICE_BASE_URL}