server:
  port: ${SERVER_PORT}

application:
  title: ${APP_TITLE}
  version: ${APP_VERSION}

spring:
  application:
    name: category-service

  profiles:
    active: dev

    data:
      mongodb:
        uri: ${DATABASE_URI}

  jpa:
    open-in-view: false

  config:
    import: configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true